### ISSUE TITLE
Provide Evidence of Current Tada Features Given Merge

### ISSUE THREAD

**Issue by gkapfham** [gkapfham/tada#37]
There are currently several pull requests open and in need of review. I can see how these pull requests work when I look at their individual code changes. However, what I would like to see more of is the overall functionality of the TaDa! tool if we decide to merge all of the open pull requests.

As such, I would like to request the following information:

* For each of the individual functions inside of the speed-surprises repository, please give the signature of the function, including its name and the name of each parameter and the expected type of each parameter.
* Then, please state the know worst-case time complexity of this function, using the Big-Oh notation.
* Next, please state the likely worst-case time complexity as suggested by the TaDa! tool.
* Finally, please give a data table that was produced by TaDa! and explain how the data table supports and/or contradicts the two previous worst-case time complexities. You can give the data table as a fenced code block.

Does this make sense, @huangs1 and @Lancasterwu and @lussierc? I think that it would be fine for you to include all of these details in this issue tracker.

Also, @Lancasterwu you mentioned that there was a bug in the code that you found at the last minute &mdash; can you please explain what it was how and you fixed it?

Once we have discussed everything in this issue and I have a clear global picture then we can merge the pull requests and start to prioritize the features that we implement next. Thanks!

**Comment by lussierc** [comment]
I think this is an excellent idea @gkapfham and we will begin to work on this shortly! We will compile evidence of the features that would be added via merges of current pull requests and post them in this Issue.

**Comment by gkapfham** [comment]
Thanks for agreeing to work on this @lussierc and @Lancasterwu and @huangs1!

**Comment by gkapfham** [comment]
Are you going to place the content here? Or, in the separate PRs? Please let me know where I need to look, okay?

**Comment by lussierc** [comment]
Hi @gkapfham , I plan on placing the content you requested in this Issue. We will also take the time to add information to the individual pull requests if necessary.

**Comment by Lancasterwu** [comment]
> Also, @Lancasterwu you mentioned that there was a bug in the code that you found at the last minute — can you please explain what it was how and you fixed it?

Hi @gkapfham, The bug was related to the test case in `results.py`. I was only testing if the result table can be built with the input, but I didn't test if the output is expected output so there was a code coverage issue. @huangs1 solved that issue by adding more test case.

**Comment by gkapfham** [comment]
Thanks for adding more test cases @huangs1. If you have not done so already, please try to add as many Pytest test cases as is possible so that we can have high coverage of the new features that you are adding, @Lancasterwu. Also, @lussierc, I look forward to reviewing the content that you prepare to show that the new features are working correctly!

**Comment by huangs1** [comment]
# TaDa! Functionality Information
This information was contributed by: @lussierc, @huangs1, and @lancasterwu.


## Iterative Factorial
This function (`compute_iterative_factorial`) computes factorial numbers using an iterative approach. The data type utilized for calculating this number is an integer and it is called "value".

[Iterative Factorial Function Pull Request in S-S](https://github.com/gkapfham/speed-surprises/pull/6)
### Known Worst-Case Time Complexity
The known worst-case time complexity for the Iterative Factorial is O(n).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
| 100  | 7.4825469106124904e-06 | 7.4258849792618875e-06 |         0          |
| 200  | 1.6761786645513866e-05 | 1.674106481952542e-05  | 2.2401178162666295 |
| 400  |  4.52228422973248e-05  | 4.5129400757293325e-05 | 2.6979726716321295 |
| 800  | 0.00014487455328774008 | 0.00014286444140765298 | 3.2035702739610925 |
| 1600 |  0.000525010508203394  | 0.0005191467500011981  | 3.623897339380598  |
| 3200 | 0.0019217860250004529  | 0.0018753224531451451  | 3.6604715428970707 |
+------+------------------------+------------------------+--------------------+
```

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 7.928134142313562e-06  | 7.670978796170402e-06  |
| 200  | 1.7774744406059048e-05 | 1.7460589788242942e-05 |
| 400  | 4.714114836209168e-05  | 4.676695189687052e-05  |
| 800  | 0.0001440876215345573  | 0.00014266396738094045 |
| 1600 |  0.000500340734515703  | 0.0004883888791482605  |
| 3200 | 0.001887952622564626   | 0.001887952622564626   |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files
```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.7953341539978283  |     0.43         |   100  | 0.7548120128922164  |      0.35        |
200  | 0.9491631069977302  |     0.56         |   200  | 0.7445043679326773  |      0.49        |
400  | 0.6387701829989965  |     0.66         |   400  | 1.0327511578798294  |      1.1         |
800  | 1.0093401679987437  |     0.73         |   800  | 0.8114936600904912  |      2.12        |
1600 | 0.8400330830008897  |     0.96         |   1600 | 0.6584241029340774  |      2.09        |
3200 | 0.8226098859995545  |     1.12         |   3200 | 0.6027577088680118  |      1.85        |
```

## Recursive Factorial
This function (`compute_recursive_factorial`) computes factorial numbers using an iterative approach. The data type utilized for calculating this number is an integer and it is called "value".

[Recursive Factorial Function Pull Request in S-S](https://github.com/gkapfham/speed-surprises/pull/6)
### Known Worst-Case Time Complexity
The worst-case time complexity for Recursive Factorial is O(n).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
| 100  | 1.758986948648585e-05  | 1.7327522460863776e-05 |         0          |
| 200  | 3.9576942871126046e-05 |  3.92657760013293e-05  | 2.249985021294938  |
| 400  | 0.00010340916247567241 | 0.00010317998754860724 | 2.6128638286287678 |
| 800  | 0.0002876200094731255  | 0.00028576612402275714 | 2.7813783864731496 |
+------+------------------------+------------------------+--------------------+
```

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 1.3326765937430689e-05 | 1.3256493602398223e-05 |
| 200  | 3.29582902357591e-05   | 3.246977820481334e-05  |
| 400  | 7.709862748204918e-05  | 7.584915607594667e-05  |
| 800  | 0.00020373904975864814 | 0.00020341778417787282 |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.7778829499984568  |     0.62         |   100  | 0.578903327928856   |      0.69        |
200  | 0.7867775459999393  |     0.84         |   200  | 0.7075475859455764  |      0.76        |
400  | 0.9543355189998692  |     0.95         |   400  | 0.8390595780219883  |      0.89        |
800  | 0.7023630910007341  |     1.11         |   800  | 0.5557957750279456  |      0.92        |
```

## Recursive Hashmap Factorial
This function (`compute_hashmap_recursive_factorial`) computes factorial numbers using an iterative approach. The data type utilized for calculating this number is an integer and it is called "value".

[Recursive Hashmap Factorial Function Pull Request in S-S](https://github.com/gkapfham/speed-surprises/pull/6)
### Known Worst-Case Time Complexity
The known worst came time complexity for this function is O(n^2).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
| 100  | 2.4395564286194827e-05 | 2.4321165771112874e-05 |         0          |
| 200  | 5.440036750433327e-05  | 5.392505712720208e-05  | 2.2299286405569156 |
| 400  | 0.00013258158339747675 | 0.0001308187949149442  | 2.437144995149453  |
| 800  | 0.0004178569479165617  | 0.0004063718886584411  | 3.151696768199211  |
+------+------------------------+------------------------+--------------------+
```
The ratio starts around 2.23 and begins to increase.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 2.4820835152657614e-05 | 2.471492504696471e-05  |
| 200  | 5.9198781893125364e-05 | 5.990454855009375e-05  |
| 400  | 0.00014464055668289195 | 0.00014612942140956875 |
| 800  | 0.0004970849815132775  | 0.0004990148945580586  |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.6716658799996367  |     0.57         |   100  | 0.5448615020141006  |      1.4         |
200  | 0.7029708890004258  |     0.73         |   200  | 0.5693390478845686  |      1.39        |
400  | 0.8573264810002001  |     0.79         |   400  | 0.80674973805435    |      1.8         |
800  | 0.6731039730002522  |     0.91         |   800  | 0.5378257879056036  |      1.83        |
```

## Recursive Fibonacci
This function (`compute_recursive_fibonacci`) computes fibonacci numbers using a recursive approach. The data type utilized for calculating this number is an integer and it is called "value".

[Recursive Fibonacci Function Pull Request in S-S](https://github.com/gkapfham/speed-surprises/pull/7)
### Known Worst-Case Time Complexity
The known worst came time complexity for this function is O(2^n).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
|  5   | 1.3897040884650971e-06 | 1.3754905357488134e-06 |         0          |
|  10  | 1.4610726930571379e-05 | 1.4561544738000975e-05 | 10.513552526645194 |
|  20  |  0.001771996459892004  | 0.0017715385781684745  | 121.28051316764339 |
+------+------------------------+------------------------+--------------------+
```
For the sake of time, we only ran three rounds of small sizes of the doubling experiment for Recursive Fibonacci because it can be extremely time and memory consuming.

The ratio seems to rapidly grow, jumping from 0 to 10.5 to 121.3. which is expected because of how it noticeably runs slower as the size is doubled.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 5    | 1.5259351860900475e-06 | 1.531375009022895e-06  |
| 10   | 1.5180993624615743e-05 | 1.4865913328776514e-05 |
| 20   | 0.00183482656157139    | 0.0018128080773749389  |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
5   | 0.6687934869987657  |      4.93         |   100  | 0.5523125741165131  |      0.76        |
10  | 0.8531704670022009  |      4.28         |   200  | 0.6880263488274068  |      1.03        |
20  | 0.8070432650019939  |      3.55         |   400  | 0.6300236908718944  |      1.17        |
```

## Iterative Fibonacci
This function (`compute_iterative_fibonacci`) computes fibonacci numbers using an iterative approach. The data type utilized for calculating this number is an integer and it is called "value".

[Iterative Fibonacci Function Pull Request in S-S](https://github.com/gkapfham/speed-surprises/pull/7)
### Known Worst-Case Time Complexity
The known worst came time complexity for this function is O(n).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+-----------------------+------------------------+--------------------+
| Size |          Mean         |         Median         |       Ratio        |
+------+-----------------------+------------------------+--------------------+
| 100  | 4.316666885887758e-06 | 4.243041961782268e-06  |         0          |
| 200  | 8.640653300003483e-06 | 8.554210236155768e-06  | 2.0016956435188216 |
| 400  | 1.907847050572897e-05 | 1.9066346069962492e-05 | 2.2079893548930243 |
| 800  | 4.352622781151893e-05 | 4.344370447029178e-05  | 2.2814317216072784 |
+------+-----------------------+------------------------+--------------------+
```
The ratio starts at 2 and seems to begin to slightly increase.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 4.2771897015588445e-06 | 4.201349000254595e-06  |
| 200  | 9.38305634742657e-06   | 9.46054544215258e-06   |
| 400  |  2.155554474446338e-05 | 2.1685948610183914e-05 |
| 800  | 4.8233253046229645e-05 | 4.820044310349658e-05  |
| 1600 | 0.00010847376729164656 | 0.00011101978759597841 |
| 3200 | 0.00026220367540948547 | 0.0002593662165963906  |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.8005907900005695  |      0.48        |   100  | 0.7894177299458534  |      1.67        |
200  | 0.7892461440005718  |      0.83        |   200  | 0.7345029341522604  |      1.59        |
400  | 0.8671792280001682  |      1.0         |   400  | 0.9502746840007603  |      1.78        |
800  | 0.9903653729998041  |      1.08        |   800  | 0.745693382108584   |      2.12        |
1600 | 0.5722454949991516  |      1.19        |   1600 | 0.6352931391447783  |      2.39        |
3200 | 0.7179600920007942  |      1.16        |   3200 | 0.6921238917857409  |      2.51        |
```

## Insertion Sort
This function (`insertion_sort`) sorts the given array into numeric order from lowest to highest using the insertion sort method. It sorts lists.

[Pull request for insertion sorting](https://github.com/gkapfham/speed-surprises/pull/9)
### Known Worst-Case Time Complexity
The known worst came time complexity for this function is O(n^2).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
| 100  | 3.473159865688182e-07  | 3.4527655410482305e-07 |         0          |
| 200  | 3.5032915452366344e-07 | 3.4843794632227754e-07 |  1.00867558094464  |
| 400  | 3.4790232779230896e-07 | 3.465821075479547e-07  | 0.9930727240367585 |
| 800  | 3.4474864594134326e-07 | 3.4366042518663154e-07 | 0.9909351516243708 |
| 1600 | 3.4308542559852625e-07 | 3.423757762924251e-07  | 0.9951755565615767 |
| 3200 | 3.457929653803704e-07  | 3.4270542621436806e-07 | 1.0078917365175764 |
+------+------------------------+------------------------+--------------------+
```
The ratio seems to stay stagnant around 1.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 3.518818283865244e-07  | 3.5060494707472856e-07 |
| 200  | 3.502192617022004e-07  | 3.4949264327011065e-07 |
| 400  |  3.499385147431866e-07 | 3.4940742787981094e-07 |
| 800  | 3.5073733456088737e-07 | 3.4907873613931883e-07 |
| 1600 | 3.4907873613931883e-07 | 3.4998822573406585e-07 |
| 3200 | 3.4946203148293146e-07 | 3.502147882805673e-07  |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.69525823100048    |      0.39        |   100  | 0.9480864619836211  |      0.37        |
200  | 0.6928299179999158  |      0.49        |   200  | 0.9479883229359984  |      0.62        |
400  | 0.6644164220015227  |      0.68        |   400  | 0.958413760876283   |      0.73        |
800  | 0.6739351509968401  |      0.73        |   800  | 0.9864987169858068  |      0.81        |
1600 | 0.6713196379969304  |      0.93        |   1600 | 0.960950274951756   |      1.31        |
3200 | 0.7397612649983785  |      1.25        |   3200 | 0.9675539738964289  |      1.22        |
```

## Bubble Sort
This function (`bubble_sort`) sorts the given array into numeric order from lowest to highest using the bubble sort method. It sorts lists.

[Pull request for bubble sorting](https://github.com/gkapfham/speed-surprises/pull/9)
### Known Worst-Case Time Complexity
The known worst came time complexity for this function is O(n^2).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
| 100  | 3.7595076230409937e-07 | 3.730039663321638e-07  |         0          |
| 200  | 3.8558718074207613e-07 | 3.754900665293992e-07  | 1.0256321290025263 |
| 400  | 3.981998148600933e-07  |  3.9382985687203e-07   | 1.032710200826033  |
| 800  | 3.8170006507233974e-07 | 3.752909698458151e-07  | 0.9585641450045608 |
| 1600 | 3.827891248060535e-07  | 3.8040976905670543e-07 | 1.0028531819440674 |
| 3200 | 3.846472932500511e-07  |  3.79581999779971e-07  | 1.0048542874485764 |
+------+------------------------+------------------------+--------------------+
```
The ratio seems to stay stagnant around 1.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 3.7390679443749517e-07 | 3.7363475802187907e-07 |
| 200  | 3.7422941638887154e-07 | 3.7349125303620667e-07 |
| 400  | 3.7781959660865283e-07 | 3.743938903344457e-07  |
| 800  | 3.8462285056143723e-07 | 3.8045956607390963e-07 |
| 1600 | 3.8074081291454104e-07 | 3.801757906263248e-07  |
| 3200 | 3.8023228863999967e-07 | 3.7898796834134885e-07 |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.7458850129987695  |     0.83         |   100  | 1.029424387961626   |     0.44         |
200  | 0.7288865000009537  |     1.1          |   200  | 0.9306149699259549  |     0.68         |
400  | 0.7272325029989588  |     1.31         |   400  | 1.0142612510826439  |     0.79         |
800  | 0.7118728829991596  |     1.32         |   800  | 0.5609592669643462  |     0.85         |
1600 | 0.7763208120013587  |     1.39         |   1600 | 1.0301205981522799  |     0.89         |
3200 | 0.7152749849992688  |     1.54         |   3200 | 1.0478147610556334  |     1.0          |
```

## Merge Sort
This function (`merge_sort`) sorts the given array into numeric order from lowest to highest using the merge sort method. It sorts lists.

[Pull request for Merge sorting](https://github.com/gkapfham/speed-surprises/pull/9)
### Known Worst-Case Time Complexity
The known worst-case time complexity is O(n log n).
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
| 100  | 2.2090976209641336e-07 | 2.1921813964835904e-07 |         0          |
| 200  | 2.1844482491812087e-07 | 2.1748579502091098e-07 | 0.9888418820657789 |
| 400  | 2.1659555508295514e-07 | 2.1663631057740242e-07 | 0.9915343847772137 |
| 800  | 2.1880415007272706e-07 | 2.1745333766932592e-07 | 1.0101968620220578 |
+------+------------------------+------------------------+--------------------+

```
The ratio seems to stay stagnant around 1.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 2.2228321977883306e-07 | 2.2221790785259543e-07 |
| 200  | 2.2477862928749204e-07 | 2.2287456236114167e-07 |
| 400  | 2.471121285004448e-07  | 2.4869981207764624e-07 |
| 800  | 2.481549313741264e-07  | 2.4869981207764624e-07 |
| 1600 | 2.3641497150321083e-07 | 2.4038362589351436e-07 |
| 3200 | 2.5974597763026943e-07 | 2.540409020923562e-07  |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.8788221100003284  |      0.64        |   100  | 0.6208762798923999  |      0.83        |
200  | 0.8547067079998669  |      2.16        |   200  | 0.60191760212183    |      0.85        |
400  | 0.8555539269982546  |      1.9         |   400  | 0.6134257540106773  |      0.89        |
800  | 0.8721733829988807  |      1.7         |   800  | 0.6914314047899097  |      1.52        |
1600 | 0.8498065909989236  |      1.61        |   1600 | 0.6811490191612393  |      2.93        |
3200 | 0.8482527189989923  |      2.69        |   3200 | 0.7645410259719938  |      2.88        |

```

## Boolean List Copier
Adding the two function that generates a boolean list by copying the one boolean. The first function always generates the list with boolean "True" with the input list size. The second function generates the boolean list by copying the input boolean with the input list size. Both of them have the same logic and similar code to function `mcopies_ofc` and function `mcopies_of`.

[Pull request for Boolean List Copier](https://github.com/gkapfham/speed-surprises/pull/10)
### Known Worst-Case Time Complexity
The known worst-case time complexity is O(n)
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+-----------------------+--------------------+
| Size |          Mean          |         Median        |       Ratio        |
+------+------------------------+-----------------------+--------------------+
| 100  | 8.338868666579735e-06  | 8.218750152555465e-06 |         0          |
| 200  | 1.5700233292662937e-05 | 1.540394268784162e-05 | 1.8827773790929045 |
| 400  | 3.1195413785800595e-05 | 3.099510217285939e-05 | 1.9869395062033184 |
| 800  | 6.837366451020918e-05  |  6.50304267582058e-05 | 2.1917857855545173 |
+------+------------------------+-----------------------+--------------------+

```
The ratio seems to stay stagnant around 1.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 5.802886783001781e-06  | 5.756597136752362e-06  |
| 200  | 1.1823222762075147e-05 | 1.188692831277649e-05  |
| 400  | 2.411669886441814e-05  | 2.4249597800007905e-05 |
| 800  | 4.5436102999474316e-05 | 4.5451995987377813e-05 |
| 1600 | 9.181866208412733e-05  | 9.030103882423646e-05  |
| 3200 | 0.00018533638011604127 | 0.0001835965664440664  |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.7195848879964615  |      0.58        |   100  |  0.9955107679124922 |      0.29        |
200  | 0.667840239002544   |      0.76        |   200  |  0.9533524829894304 |      0.53        |
400  | 0.7065571439998166  |      0.79        |   400  |  0.5385665739886463 |      1.19        |
800  | 0.6873425230005523  |      0.84        |   800  |  0.9474618828389794 |      1.5         |
1600 | 0.7256906260008691  |      0.94        |   1600 |  0.9846653621643782 |      1.48        |
3200 | 0.7479047240012733  |      1.18        |   3200 |  0.9541284739971161 |      1.34        |
```

## String Reverser
This function (`reverse`) reverses strings of characters. The default parameter is named "s" and it is of type String.

[Pull request for String Reverser](https://github.com/gkapfham/speed-surprises/pull/12)
### Known Worst-Case Time Complexity
The known worst-case time complexity is O(n)
### Tada's Suggested Worst-Case Time Complexity
#### Data Table From New TaDa

```
+------+------------------------+------------------------+--------------------+
| Size |          Mean          |         Median         |       Ratio        |
+------+------------------------+------------------------+--------------------+
| 100  | 2.4075920845671263e-07 | 2.373471221783774e-07  |         0          |
| 200  | 2.391247944178813e-07  | 2.379912996397504e-07  | 0.9932114162971872 |
| 400  | 2.399731260626277e-07  | 2.377495613020697e-07  | 1.0035476523746172 |
| 800  | 2.3622465397480734e-07 | 2.3491613197756944e-07 | 0.9843796172124619 |
+------+------------------------+------------------------+--------------------+
```
The ratio seems to stay stagnant around 1.

#### Data Table from Old TaDa

```
+------+------------------------+------------------------+
| Size |          Mean          |         Median         |
+------+------------------------+------------------------+
| 100  | 2.48963649777482e-07   | 2.4555271438408965e-07 |
| 200  | 2.489376444018513e-07  | 2.475851401673168e-07  |
| 400  | 2.519319706702679e-07  | 2.4808318110913774e-07 |
| 800  | 2.749085059964666e-07  | 2.6974251543521177e-07 |
| 1600 | 2.707979977885818e-07  | 2.6872205372008295e-07 |
| 3200 | 2.671094392188896e-07  | 2.6760378935009044e-07 |
+------+------------------------+------------------------+
```

#### Information pulled from JSON files

```
              New                             |                  Old                            |
----------------------------------------------|-------------------------------------------------|
Size |      Duration       | load_avg_1min    |   Size |      Duration       | load_avg_1min    |
----------------------------------------------|-------------------------------------------------|
100  | 0.6858877630002098  |      0.37        |   100  | 0.7295905379578471  |      0.97        |
200  | 0.6762002569994365  |      0.51        |   200  | 0.6822095368988812  |      1.06        |
400  | 0.6848723670009349  |      0.66        |   400  | 0.687261771876365   |      1.29        |
800  | 0.7624338180030463  |      1.13        |   800  | 0.762441033963114   |      1.54        |
1600 | 0.6891136070007633  |      1.23        |   1600 | 0.7458477939944714  |      1.97        |
3200 | 0.7557480149989715  |      1.18        |   3200 | 0.732519713928923   |      2.14        |
```

**Comment by lussierc** [comment]
In terms of how many worst-case time complexities the Tada, most things seem to be accurate in terms of the ratios calculated by Tada matching the expected worst-case big-O time complexity.

Here is a breakdown:
- **Iterative Factorial:** The known worst-case time complexity is O(n). Tada calculates a ratio of around 2 for the most part, ranging from 2-3. This ratio implies it could be O(n). ✔️
- **Recursive Factorial:** The known worst-case time complexity is O(n). Tada calculates a ratio of around 2, implying that the ratio is O(n). ✔️
- **Recursive Hashmap Factorial:** The known worst-case time complexity is O(n log n). Though we did not do many rounds for this experiment for time reasons, it seems to be fairly accurate and the ratio is around 2, implying it is linearithmic and O(n log n). ✔️
- **Recursive Fibonacci:** The known worst-case time is O(2^n), meaning it is exponential. The ratio sees a large increase and what seems like exponential growth. ✔️
- **Iterative Fibonacci:** The known worst-case time complexity is O(n). The ratio calculated by Tada hovers around 2, implying that it is O(n). ✔️
- **Insertion Sort:** The known worst-case time complexity for this function is O(n^2). The ratio calculated by Tada hovers around 1, ranging from .99 to 1. This would imply that is constant, or O(1). This is likely because this is the best case time complexity, not the worst-case time complexity of O(n^2) which would likely take several hours of running the benchmark to appear.
- **Bubble Sort:** The known worst-case time complexity for this function is O(n^2). The ratio calculated by Tada hovers around 1, ranging from .95 to 1.03. This would imply that is constant, or O(1). This is likely because this is the best case time complexity, not the worst-case time complexity of O(n^2) which would likely take quite a while running the benchmark to appear.
- **Merge Sort:** The known worst-case time complexity is O(n log n). The ratio calculated by Tada is around 1. This would imply that is constant, or O(1). This is likely because this is the best case time complexity, not the worst-case time complexity of O(n log n) which would likely take quite a while running the benchmark to appear.
- **Boolean List Copier**: The known worst-case time complexity is O(n). Tada's calculated ratio hovers around 2, ranging from 1.88 to 2.19 from the rounds ran. This would imply that the worst case time complexity is O(n), which is usually around a ratio of 2. ✔️
- **String Reverser**: The known worst-case time complexity is O(n). The ratio stays around 1, which would imply it is constant or O(1). We would likely need to run this for longer to be sure.

Overall, it seems to be fairly accurate with 6 of the functions passing the eye test in terms of whether the ratio is accurate relative to the known worst-case time complexity ratio. However, there are 4 of the functions that Tada-calculated ratios are lower than expected, likely because the experiment was not run for long enough/big enough sizes. It is likely that if we ran these benchmarks for longer, the expected worst-case time would begin to appear in the ratios. It would be a good idea to try and take the time to run these for longer to be sure.
